# Generated by Django 5.2.9 on 2025-12-21 08:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisParameters',
            fields=[
                ('parameter_id', models.AutoField(db_column='ParameterID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=20, null=True)),
                ('min_value', models.DecimalField(blank=True, db_column='MinValue', decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, db_column='MaxValue', decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'AnalysisParameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barns',
            fields=[
                ('barn_id', models.AutoField(db_column='BarnID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('capacity', models.IntegerField(db_column='Capacity')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Barns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CowBiologicalAnalysis',
            fields=[
                ('analysis_id', models.AutoField(db_column='AnalysisID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('value', models.DecimalField(blank=True, db_column='Value', decimal_places=2, max_digits=10, null=True)),
                ('result', models.CharField(blank=True, db_column='Result', max_length=50, null=True)),
            ],
            options={
                'db_table': 'CowBiologicalAnalysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CowFeeding',
            fields=[
                ('feeding_id', models.AutoField(db_column='FeedingID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'CowFeeding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CowHealth',
            fields=[
                ('health_id', models.AutoField(db_column='HealthID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('type', models.CharField(db_column='Type', max_length=50)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('vet_name', models.CharField(blank=True, db_column='VetName', max_length=100, null=True)),
                ('next_checkup_date', models.DateField(blank=True, db_column='NextCheckupDate', null=True)),
            ],
            options={
                'db_table': 'CowHealth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cows',
            fields=[
                ('cow_id', models.AutoField(db_column='CowID', primary_key=True, serialize=False)),
                ('ear_tag_number', models.CharField(db_column='EarTagNumber', max_length=50, unique=True)),
                ('breed', models.CharField(blank=True, db_column='Breed', max_length=50, null=True)),
                ('date_of_birth', models.DateField(db_column='DateOfBirth')),
                ('gender', models.CharField(db_column='Gender', max_length=10)),
                ('weight', models.DecimalField(blank=True, db_column='Weight', decimal_places=2, max_digits=10, null=True)),
                ('health_status', models.CharField(blank=True, db_column='HealthStatus', max_length=50, null=True)),
                ('last_milking_date', models.DateField(blank=True, db_column='LastMilkingDate', null=True)),
            ],
            options={
                'db_table': 'Cows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('role', models.CharField(db_column='Role_', max_length=50)),
                ('base_salary', models.DecimalField(db_column='BaseSalary', decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(db_column='HourlyRate', decimal_places=2, max_digits=10)),
                ('hire_date', models.DateField(db_column='HireDate')),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTasks',
            fields=[
                ('task_id', models.AutoField(db_column='TaskID', primary_key=True, serialize=False)),
                ('task_description', models.CharField(blank=True, db_column='TaskDescription', max_length=255, null=True)),
                ('hours_worked', models.DecimalField(blank=True, db_column='HoursWorked', decimal_places=2, max_digits=5, null=True)),
                ('task_date', models.DateField(db_column='TaskDate')),
            ],
            options={
                'db_table': 'EmployeeTasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(db_column='FoodID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('type', models.CharField(db_column='Type', max_length=50)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=20, null=True)),
                ('reorder_level', models.DecimalField(blank=True, db_column='ReorderLevel', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('analysis_id', models.AutoField(db_column='AnalysisID', primary_key=True, serialize=False)),
                ('analysis_date', models.DateField(db_column='AnalysisDate')),
                ('value', models.DecimalField(blank=True, db_column='Value', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'FoodAnalysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptDetails',
            fields=[
                ('grn_detail_id', models.AutoField(db_column='GRNDetailID', primary_key=True, serialize=False)),
                ('received_quantity', models.DecimalField(db_column='ReceivedQuantity', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'GoodsReceiptDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptNotes',
            fields=[
                ('grn_id', models.AutoField(db_column='GRNID', primary_key=True, serialize=False)),
                ('receipt_date', models.DateField(db_column='ReceiptDate')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'GoodsReceiptNotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('machine_id', models.AutoField(db_column='MachineID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('last_maintenance', models.DateField(blank=True, db_column='LastMaintenance', null=True)),
                ('next_maintenance', models.DateField(blank=True, db_column='NextMaintenance', null=True)),
            ],
            options={
                'db_table': 'Machines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MilkAnalysis',
            fields=[
                ('analysis_id', models.AutoField(db_column='AnalysisID', primary_key=True, serialize=False)),
                ('analysis_date', models.DateField(db_column='AnalysisDate')),
                ('value', models.DecimalField(blank=True, db_column='Value', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'MilkAnalysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('production_id', models.AutoField(db_column='ProductionID', primary_key=True, serialize=False)),
                ('production_date', models.DateField(db_column='ProductionDate')),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
                ('quality', models.CharField(blank=True, db_column='Quality', max_length=100, null=True)),
            ],
            options={
                'db_table': 'MilkProduction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(db_column='OrderedQuantity', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PurchaseOrderItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('order_id', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('order_date', models.DateField(db_column='OrderDate')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PurchaseOrders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resource_id', models.AutoField(db_column='ResourceID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=20, null=True)),
                ('reorder_level', models.DecimalField(blank=True, db_column='ReorderLevel', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('part_id', models.AutoField(db_column='PartID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('reorder_level', models.IntegerField(db_column='ReorderLevel')),
            ],
            options={
                'db_table': 'SpareParts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(db_column='SupplierID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('contact_info', models.CharField(blank=True, db_column='ContactInfo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User_Auth',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
